#!/usr/bin/env python3
from ocflib.infra.hosts import hosts_by_filter

desktops = hosts_by_filter('(|(type=desktop)(dnsCname=pi))')

for desktop in desktops:
    print('host {} {{ hardware ethernet {}; fixed-address {}; }}'.format(
        desktop['cn'][0],
        desktop['macAddress'][0],
        desktop['ipHostNumber'][0],
    ))
