#!/bin/bash -e
# Test if the mirror hasn't been updated in 24 hours. This can happen if the
# upstream mirror fails to sync, but we sync successfully with our upstream
# mirror.

# ubuntu has no symlinks for any of its releases (either stable or unstable),
# so we can't just always check the same dist, like we can with debian :\
#
# instead, we used to use a terrible "list all the releases and sort them
# alphabetically, then grab the last" thing to find the latest release, which
# should have worked until ubuntu wraps around
#
# but turns out it doesn't, so we hard-code the release until we figure out a
# better way :\
dist="trusty-updates"
updated=$(curl -s "http://mirrors/ubuntu/dists/$dist/Release" | \
	grep Date | cut -d':' -f2- | sed -s 's/^ //')
updated_epoch=$(date --date="$updated" +%s) # last update (seconds since 1970)

yesterday=$(($(date +%s) - 24 * 60 * 60))

if [ "$updated_epoch" -lt "$yesterday" ]; then
	echo "Warning: ubuntu has not been updated since $(date --date="$updated")"
	exit 1
fi
