#!/bin/bash -e
# Test if the mirror hasn't been updated in 24 hours. This can happen if the
# upstream mirror fails to sync, but we sync successfully with our upstream
# mirror.

# ubuntu has no symlinks for any of its releases (either stable or unstable),
# so we can't just always check the same dist, like we can with debian :\
#
# instead, we use this terrible thing to find the latest release (sorted
# alphabetically...), which ought to work until ubuntu wraps around
#
# (so we get a few more releases before needing to fix this...)
dist=$(curl -s http://mirrors.ocf.berkeley.edu/ubuntu/dists/ | \
	sed -nr 's/.*<td><a href="([a-z]*)\/".*/\1/p' | sort | tail -n1)
# the stable repo does not always get updates, but we suspect -updates will
dist="${dist}-updates"

updated=$(curl -s "http://mirrors/ubuntu/dists/$dist/Release" | \
	grep Date | cut -d':' -f2- | sed -s 's/^ //')
updated_epoch=$(date --date="$updated" +%s) # last update (seconds since 1970)

# XXX: for ubuntu we use a 48 hour check, since 24 hours causes false positives
two_yesterdays=$(($(date +%s) - 24 * 60 * 60 * 2))

if [ "$updated_epoch" -lt "$two_yesterdays" ]; then
	echo "Warning: ubuntu has not been updated since $(date --date="$updated")"
	exit 1
fi
