#!/bin/bash -e
SITE_CFG='/etc/nginx/sites-enabled/virtual'
TEMP=$(mktemp)

(
grep '^[a-z]' ~staff/vhost/vhost-app.conf | \
while read line; do
	user=$(cut -d' ' -f1 <<< $line)
	vhost=$(cut -d' ' -f2 <<< $line)
	socket=$(cut -d' ' -f3 <<< $line)

	if [ "$socket" == "-" ]; then
		socket="$user"
	fi

	if [ "$vhost" == "-" ]; then
		vhost="$user"
	fi

	if ! grep '\.' <<< "$vhost" > /dev/null; then
		vhost="${vhost}.berkeley.edu"
	fi

	# vhost alias under apphost.ocf.berkeley.edu
	vhost_dev=$(sed 's/\./-/g' <<< "$vhost").apphost.ocf.berkeley.edu

	socket_dir="/srv/apps/$user"
	socket_file="$socket_dir/${socket}.sock"

	if ! groups "$user" | grep '\bocfdev\b' > /dev/null; then
		echo "Warning: $user not in group ocfdev but has app vhost:" >&2
		echo "$user: $vhost at $socket_file" >&2
	fi

	[ -d "$socket_dir" ] || mkdir "$socket_dir"
	chown "${user}:ocf" "$socket_dir"
	chmod 755 "$socket_dir"

	cat <<EOF
server {
	listen 80;
	server_name "$vhost" "$vhost_dev";
	location / {
		proxy_pass http://unix:${socket_file};
		proxy_set_header Host \$host;
		proxy_set_header X-Forwarded-For \$remote_addr;
		proxy_set_header X-Real-IP \$remote_addr;
	}
}
EOF
done
) > "$TEMP"

if [ ! -f "$SITE_CFG" ] || ! diff "$SITE_CFG" "$TEMP"; then
	mv "$TEMP" "$SITE_CFG"
	echo "Things changed, reloading nginx..."
	/usr/sbin/service nginx reload
else
	echo "Nothing changed."
	rm "$TEMP"
fi
