#!/bin/bash -e
SITE_CFG='/etc/nginx/sites-enabled/virtual'
TEMP=$(mktemp)

(
grep '^[a-z]' ~staff/vhost/vhost-app.conf | \
while read line; do
	user=$(cut -d' ' -f1 <<< $line)
	vhost=$(cut -d' ' -f2 <<< $line)
	socket=$(cut -d' ' -f3 <<< $line)
	ssl_name=$(cut -d' ' -f4 <<< $line)

	config_end=""

	if [ "$socket" == "-" ]; then
		socket="$user"
	fi

	if [ "$vhost" == "-" ]; then
		vhost="$user"
	fi

	if ! grep '\.' <<< "$vhost" > /dev/null; then
		vhost="${vhost}.berkeley.edu"
	fi

	if [ "$ssl_name" == "-" ]; then
		port=80
	else
		port=443
		config_end="$config_end
		ssl on;
		ssl_certificate /etc/ssl/apphost/${ssl_name}.bundle;
		ssl_certificate_key /etc/ssl/private/apphost/${ssl_name}.key;
		add_header Strict-Transport-Security \"max-age=31536000\";"

	fi

	# vhost alias under apphost.ocf.berkeley.edu
	vhost_dev=$(sed 's/\./-/g' <<< "$vhost").apphost.ocf.berkeley.edu

	socket_dir="/srv/apps/$user"
	socket_file="$socket_dir/${socket}.sock"

	if ! groups "$user" | grep '\bocfdev\b' > /dev/null; then
		echo "Warning: $user not in group ocfdev but has app vhost:" >&2
		echo "$user: $vhost at $socket_file" >&2
	fi

	[ -d "$socket_dir" ] || mkdir "$socket_dir"
	chown "${user}:ocf" "$socket_dir"
	chmod 755 "$socket_dir"

	cat <<EOF
server {
	listen $port;
	listen [::]:$port;
	server_name "$vhost" "$vhost_dev";
	location / {
		proxy_pass http://unix:${socket_file};
		proxy_set_header Host \$host;
		proxy_set_header X-Forwarded-For \$remote_addr;
		proxy_set_header X-Real-IP \$remote_addr;
	}

	$config_end
}
EOF

	# https redirect vhost
	if [ "$ssl_name" != "-" ]; then
		cat <<EOF
server {
	listen 80;
	listen [::]:80;
	server_name "$vhost" "$vhost_dev";
	return 301 https://\$server_name\$request_uri;
}
EOF
	fi
done
) > "$TEMP"

if [ ! -f "$SITE_CFG" ] || ! diff -u "$SITE_CFG" "$TEMP"; then
	mv "$TEMP" "$SITE_CFG"
	echo "Things changed, reloading nginx..."
	/usr/sbin/service nginx reload
else
	echo "Nothing changed."
	rm "$TEMP"
fi
