#!/bin/bash -eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
(
    echo "====== Available arrays: ======"
    mdadm --detail --scan

    echo "====== Array information: ======"
    mdadm --detail --scan | awk '{print $2}' | while read device; do
        echo "=== Details for device '$device' ==="
        mdadm --detail "$device" |
            grep -v 'Events : ' |
            grep -v 'Update Time : ' |
            grep -vE 'State : (clean|active)\s*$'
    done
) \
> /var/lib/mdraid.new

if [ -f /var/lib/mdraid ]; then
    diff -u /var/lib/mdraid /var/lib/mdraid.new || true
fi

mv /var/lib/mdraid.new /var/lib/mdraid
