#!/usr/bin/env python
import ldap

LDAP_SERVER = "ldaps://ldap.ocf.berkeley.edu/"
LDAP_BASE = "ou=Hosts,dc=OCF,dc=Berkeley,dc=EDU"

l = ldap.initialize(LDAP_SERVER)
l.simple_bind_s("", "")

attrs = ("cn", "ipHostNumber")

for _, vals in l.search_st(LDAP_BASE, ldap.SCOPE_SUBTREE, "(type=*)", attrs):
	cn, ip = map(lambda key: vals[key][0], attrs)

	if cn.startswith("hozer-"):
		continue

	print("[{}.ocf.berkeley.edu]".format(cn))
	print("\taddress {}".format(ip))
