apiVersion: v1
kind: PersistentVolume
metadata:
  name: discourse-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/homes/services/discourse
    server: filehost.ocf.berkeley.edu
    readOnly: false
