# Mitigate Dirty Frag LPE (https://github.com/V4bel/dirtyfrag)
# Prevent loading of vulnerable kernel modules: esp4, esp6, rxrpc
install esp4 /bin/false
install esp6 /bin/false
install rxrpc /bin/false
