#!/bin/sh

if [ -n "$1" ]; then
  environment="$1"
else
  environment="production"
fi

puppetdir="/opt/puppet/env/$environment"

# validate for parser errors
manifests="`find $puppetdir -name '*.pp' -print`"
echo "$manifests" | xargs puppet parser validate || exit 1

# validate erb files
templates="`find $puppetdir -name '*.erb' -print`"
for template in $templates; do
  echo -n "$template: "
  cat "$template" | erb -x -P -T -| ruby -c || exit 1
done

echo

# lint for style errors
for manifest in $manifests; do
  lint="`puppet-lint --no-80chars-check $manifest`"
  [ -n "$lint" ] && ( echo "$lint"; echo "puppet-lint: $manifest"; exit 1 )
done
