#!/bin/bash -e
# Trigger a puppet agent run

if service puppet status > /dev/null; then
	# A bug in recent versions prevents USR1 from triggering a run:
	# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769621
	if [ "$(cat /etc/debian_version)" == 'jessie/sid' ]; then
		echo "Warning: restarting agent (bug #769621)" 2>&1
		systemctl restart puppet
	else
		kill -USR1 $(cat /var/run/puppet/agent.pid)
	fi
else
	echo "Error: Puppet agent does not appear to be running" >&2
	exit 255
fi
