#!/bin/bash
set -euo pipefail

# Always make sure the registry is started, no matter what fails.
trap 'systemctl start docker-registry' EXIT

# Delete all images older than a month.
deckschrubber -repos 9999 -month 1

systemctl stop docker-registry
docker run --rm \
    -v /var/lib/registry:/var/lib/registry \
    registry:2 \
    registry garbage-collect /etc/docker/registry/config.yml
