#!/bin/bash
set -euo pipefail

# set non-interactive package installation
export DEBIAN_FRONTEND=noninteractive

apt_cleanup() {
    echo "Cleaning up..."
    # Remove downloaded package archives, unused packages, and old config files. Updating is done through puppet's ::apt class.
    /usr/bin/aptitude clean --quiet > /dev/null
    /usr/bin/aptitude purge --assume-yes --quiet '?garbage' > /dev/null
    /usr/bin/aptitude purge --assume-yes --quiet '?config-files' > /dev/null
}

# delay for open file descriptors before running fuser, Debian bug #629048
sleep 1

# only proceed if APT and dpkg are not in use
if ! ([ -f /var/lock/aptitude ] || fuser -s /var/lock/aptitude 2> /dev/null ||
      [ -f /var/lib/dpkg/lock ] || fuser -s /var/lib/dpkg/lock 2> /dev/null); then
    apt_cleanup
fi
