#!/usr/bin/env python3
import json
import os.path
import subprocess
import sys


def run_command(command_args):
    output = subprocess.check_output(command_args).decode('utf-8').splitlines()

    # Return the command output split by line with any empty lines removed
    return list(filter(None, output))


if __name__ == '__main__':
    # if virsh is not installed, give up
    if not os.path.isfile('/usr/bin/virsh'):
        sys.exit()

    # if libvirtd is not running, virsh will not be able to connect to
    # the system libvirt daemon
    if subprocess.call(('/bin/systemctl', 'is-active', '--quiet', 'libvirtd')) != 0:
        sys.exit()

    vms_all = run_command(('/usr/bin/virsh', 'list', '--name', '--all'))
    vms_inactive = run_command(('/usr/bin/virsh', 'list', '--name', '--inactive'))

    print(json.dumps(
        {
            'vms': vms_all,
            'vms_off': vms_inactive,
            'vms_on': list(set(vms_all) - set(vms_inactive)),
        },
    ))
