#!/bin/bash -eu
# Creates a MySQL backup in the current directory. Intended to be called by
# rsnapshot.
set -o pipefail
mysqldump \
    --defaults-file=/opt/share/backups/my.cnf \
    --events \
    --all-databases --single-transaction | \
    pigz > "mysql-$(date +%F).sql.gz"
