#!/usr/bin/env python3
# Check rsnapshot backups to ensure they're actually happening and rotating
# when we expect them to.
import os.path
from datetime import datetime
from datetime import timedelta


BACKUP_PATH = '/opt/backups/rsnapshot/{interval}.0'
GRACE_PERIOD = timedelta(days=3)
INTERVALS = (
    ('daily', timedelta(days=1)),

    # last daily backup is 7 days old, and we rotate every 7 days
    ('weekly', timedelta(days=7 + 7)),

    # last weekly backup is 35 days old, and we rotate every ~31 days
    ('monthly', timedelta(days=35 + 31)),
)


if __name__ == '__main__':
    for name, delta in INTERVALS:
        path = BACKUP_PATH.format(interval=name)

        if not os.path.exists(path):
            print('For interval {}, last backup does not exist: {}'.format(
                name,
                path,
            ))
        else:
            last_backup = datetime.fromtimestamp(os.path.getmtime(path))
            age = datetime.now() - last_backup
            if age > delta + GRACE_PERIOD:
                print('For interval {}, last backup is too old:'.format(name))
                print('    - path: {}'.format(path))
                print('    - mtime: {} ({})'.format(last_backup, age))
