#!/bin/bash -eu
# Clone /opt/backups on the current host (should be pandemic) to /opt/backups
# on hal.
#
# chacha20 is significantly faster (2x speed on hal) than the default;
# this is important because CPU is the bottleneck in most cases for this copy
#
# We copy files under lock to avoid doing it while a backup takes place. We
# re-use rsnapshot's lock file because it's convenient (otherwise we'd need to
# add another check before rsnapshot runs, too).
LOCKFILE="/run/rsnapshot.pid"
(

	flock -n 9 || {
		echo "$LOCKFILE still exists, refusing to copy."
		exit 1
	}

	# rsnapshot won't run unless we remove the lockfile
	trap "rm \"$LOCKFILE\"" EXIT

	kinit -t /opt/share/backups/ocfbackups.keytab ocfbackups \
		rsync -aH --delete --partial --numeric-ids \
			--rsync-path="sudo /usr/bin/rsync" \
			-e 'ssh -c chacha20-poly1305@openssh.com' \
			/opt/backups/ ocfbackups@hal:/opt/backups/mirror/
) 9>"$LOCKFILE"
