#!/bin/bash -eu
# Create an encrypted backup (in 5 GB pieces) inside our scratch space.
#
# This can be put on a hard drive and stored under the SM's mattress, uploaded
# to Google Nearline, etc.
set -o pipefail

# Quiet mode is off by default (show pv output)
QUIET=false

# If -q is provided, turn on quiet mode
while getopts "q" opt; do
    case $opt in
        q)
            QUIET=true
            ;;
        \?)
            # Invalid option, just exit
            exit 1
            ;;
    esac
done

ARCHIVE_DIRECTORY="/opt/backups/scratch/archive"
TARGET_VOLUME="/dev/vg-backups/backups-live"
SNAPSHOT_PATH="/dev/vg-backups/backups-snapshot"

# import staff keys into temporary gpg dir
gpgdir=$(mktemp -d)
gpg --homedir "$gpgdir" --quiet --import /opt/share/backups/keys/*.asc

# make a LVM snapshot
if [ -e "$SNAPSHOT_PATH" ]; then
    echo "Snapshot already exists: ${SNAPSHOT_PATH}" >&2
    exit 1
fi

# try really hard to remove logical volume on exit
cleanup() {
    if [ -e "$SNAPSHOT_PATH" ]; then
        echo "Removing logical volume: $SNAPSHOT_PATH"
        /sbin/lvremove -f "$SNAPSHOT_PATH"
    fi
}
trap cleanup EXIT

# we don't have *quite* enough space to make a snapshot with the full 2TB of
# disk space, so we make a large enough snapshot that we'll *probably* avoid
# trouble
/sbin/lvcreate -L 500G --snapshot --name "$SNAPSHOT_PATH" "$TARGET_VOLUME"

umask 077
rm -rf "$ARCHIVE_DIRECTORY"
mkdir "$ARCHIVE_DIRECTORY"

compress_and_encrypt() {
    dd if="$SNAPSHOT_PATH" bs=32M | pigz |
        gpg --homedir "$gpgdir" \
            --quiet \
            --encrypt \
            --trust-model always \
            --compress-algo none \
            --recipient ckuehl@berkeley.edu \
            --recipient willh@ocf.berkeley.edu \
            --recipient jvperrin@ocf.berkeley.edu \
            --recipient mattmcal@ocf.berkeley.edu
}

split_parts() {
    split -d -a 4 -b 5G - \
        "${ARCHIVE_DIRECTORY}/backup-$(date +%Y-%m-%d).img.gz.gpg.part"
}

if [ "$QUIET" = true ]; then
    compress_and_encrypt | split_parts
else
    compress_and_encrypt | pv | split_parts
fi
