#!/usr/bin/env python3
# Turns kiosk monitor on/off when the lab is open/closed
import os
from datetime import datetime
from collections import defaultdict

LAB_HOURS = defaultdict(lambda: lambda x: 9 <= x <= 18) # weekdays: 9am-6pm
LAB_HOURS[5] = lambda x: 11 <= x <= 18 # saturdays: 11am-6pm
LAB_HOURS[6] = lambda x: 12 <= x <= 17 # sundays: 12pm-5pm

# is the lab open?
now = datetime.now()

if LAB_HOURS[now.weekday()](now.hour):
	os.system("/usr/bin/tvservice --preferred")
else:
	os.system("/usr/bin/tvservice --off")
