#!/bin/bash
# adopted from https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Rsync

OPTS=(--quiet --recursive --links --perms --times -D --delete --timeout=300 --checksum)

#Uncomment the following line only if you have been granted access to masterportage.gentoo.org
#SRC="rsync://masterportage.gentoo.org/gentoo-portage"

SRC="rsync://rsync.us.gentoo.org/gentoo-portage" # for the rest of the world
DST="/opt/mirrors/ftp/gentoo-portage/"

echo "Started update at" "$(date)" >> "$0".log 2>&1
logger -t rsync "re-rsyncing the gentoo-portage tree"
/usr/bin/rsync "${OPTS[@]}" "${SRC}" "${DST}" >> "$0".log 2>&1

echo "End: " "$(date)" >> "$0".log 2>&1
