#!/usr/bin/env python3
"""Enforce OCF account password complexity

When run as a script, it can be used as a Heimdal Kerberos external
password quality program. When run as a module, the complexity function
will raise a PasswordError exception if the password is weak.
"""

import re
import sys

import ocflib.account.utils as utils
import ocflib.account.validators as validators


if __name__ == '__main__':
    data = {}
    while True:
        line = sys.stdin.readline().rstrip('\n')
        if line == 'end' or not line:
            break
        else:
            line = line.split(':')
            try:
                data[line[0]] = line[1][1:]
            except:
                print("Could not parse input: " + str(line), file=sys.stderr)
                sys.exit(1)
    try:
        username = utils.extract_username_from_principal(data['principal'])
        password = data['new-password']
    except (KeyError, ValueError):
        print("Did not receive principal or password from input", file=sys.stderr)
        sys.exit(1)
    else:
        try:
            validators.validate_password(username, password)
        except ValueError as e:
            print(e, file=sys.stderr)
        else:
            print("APPROVED")
