#!/bin/sh -e

DIR="/var/backups/kerberos"

umask 077
export GIT_WORK_TREE="$DIR"
export GIT_DIR="$DIR/.git"
[ -d "$GIT_WORK_TREE" ] || mkdir "$GIT_WORK_TREE"
[ -d "$GIT_DIR" ] || git init -q
dumpfile="$DIR/kerberos.dump"
/usr/bin/kadmin -l dump --decrypt > "$dumpfile"
git add "$dumpfile"
git commit -q -m 'kerberos-git-backup' --allow-empty "$dumpfile"
git gc --auto --quiet
