#!/usr/bin/env python3
# Munin plugin for reporting the number of players currently on the OCF CS:GO
# server.
import socket
import sys

SERVER = ('csgo', 27015)


def get_num_players(server):
    """Returns the number of players on a Source Engine server, excluding
    bots."""

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.connect(SERVER)

    # https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO
    req = b'\xff\xff\xff\xffTSource Engine Query\x00'
    sock.send(req)

    response = sock.recv(4096)
    response = response[4:]  # cut off header
    response = response.split(b'\0', 4)[4]  # cut off 4 strings

    players, max_players, bots = map(int, response[2:5])
    return players - bots


if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] == 'config':
        print('graph_title CS:GO players')
        print('graph_vlabel players')
        print('graph_scale no')
        print('players.label players')
        sys.exit(0)

    print('players.value {}'.format(get_num_players(SERVER)))
