#!/bin/sh -e

environment=production
github_repo=ocf/puppet

echo -n "Deploying to $environment environment... "
export GIT_WORK_TREE=/opt/puppet/env/$environment
git checkout -f
git clean -fdx
echo "done."

echo -n "Pushing to GitHub... "
git push -fq git@github.com:$github_repo.git
echo "done."
