#!/usr/bin/env python3
import json
import re
import shutil
import subprocess
import sys


def strip_non_ints(string):
    return re.sub('[^0-9]', '', string)


def main():
    if not shutil.which('nvidia-smi'):
        print('NVIDIA drivers not installed; machine probably does not have NVIDIA GPUs.', file=sys.stderr)
        return

    nvidia_smi_output = subprocess.check_output(('nvidia-smi', '--query-gpu=name,index', '--format=csv,noheader'))
    nvidia_gpu_list = nvidia_smi_output.decode('utf-8').split('\n')[:-1]
    nvidia_gpu_info_dict = {}

    for gpu_string in nvidia_gpu_list:
        # gpu_index is used for determining what the numbers of the GPU's device files in /dev
        gpu_model, gpu_index = gpu_string.split(',', 1)
        # Strip all except numbers and add 'nv' in front to distinguish from number of GPUs
        # when specifying type in SLURM.
        gpu_model_number = 'nv' + strip_non_ints(gpu_model)
        nvidia_gpu_info_dict[int(gpu_index)] = gpu_model_number

    # To convert the dictionary into a Ruby hash, it's easiest to spit it out as a JSON-formatted string,
    # since all custom facts are strings by default. We convert it back into a hash in the SLURM configuration
    # templates.
    print('nvidia_gpu_info={}'.format(json.dumps(nvidia_gpu_info_dict)))


if __name__ == '__main__':
    main()
