#!/bin/sh
# wake up OCF lab machines

# don't wake up if /opt/ocf-nowakeup file exists
# (useful over breaks to conserve power)
[ ! -f /opt/ocf-nowakeup ] || exit 0

computers='
78:2b:cb:83:45:5d
78:2b:cb:83:4a:03
78:2b:cb:83:48:25
78:2b:cb:83:4a:9a
78:2b:cb:83:4c:1b
78:2b:cb:83:46:10
00:22:19:2b:75:07
00:22:19:2b:76:64
00:1d:92:4a:78:9e
00:22:19:2b:75:4c
00:22:19:2b:76:46
00:22:19:2b:75:fd
00:21:9b:37:bc:e7'

for address in $computers; do
  wakeonlan $address > /dev/null
done
