#!/bin/sh
# wake up OCF lab machines

# don't wake up if /opt/ocf-nowakeup file exists
# (useful over breaks to conserve power)
[ ! -f /opt/ocf-nowakeup ] || exit 0

# send magic packet to MAC addresses of desktops, retrieved from LDAP
ldapsearch -x -LLL -b "ou=Hosts,dc=OCF,dc=Berkeley,dc=EDU" \
	type=desktop macAddress | grep macAddress | cut -c 13- | \
while read address; do
	wakeonlan $address > /dev/null
done
