#!/usr/bin/env python3
"""Generate a list of printers to give to prometheus for stats generation"""
import json
import os
import tempfile
from sys import argv

from ocflib.infra.hosts import hosts_by_filter

hosts = []
for vals in hosts_by_filter('(type=printer)'):
    cn, ip, host_type = vals['cn'][0], vals['ipHostNumber'][0], vals['type'][0]

    hosts.append({
        'targets': [ip],
        'labels': {'instance': cn},
    })

if len(argv) < 2 or argv[1] == '-':
    print(json.dumps(hosts, indent=4))
else:
    # atomic overwrite in case of errors
    file_name = argv[1]
    with tempfile.NamedTemporaryFile(mode='w', delete=False) as temp_file:
        try:
            json.dump(hosts, temp_file, indent=4)
            os.chmod(temp_file.name, 0o644)
            os.rename(temp_file.name, file_name)
        finally:
            try:
                os.remove(temp_file.name)
            except FileNotFoundError:
                pass
