#!/bin/bash

set -uo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

version="$(puppet --version)"
if [ "$version" == "4.8.2" ] || [ "$version" == "" ]; then
  apt remove -y puppet
  apt install -y puppet-agent
  rm -rf /etc/puppetlabs/puppet/ssl
  mv /var/lib/puppet/ssl /etc/puppetlabs/puppet/
  chown root:root -R /etc/puppetlabs/puppet/ssl

  echo "Running puppet agent..."
  /opt/puppetlabs/bin/puppet agent -t

  echo "Removing old puppet directories to avoid future confusion"
  rm -r /var/lib/puppet /etc/puppet
else
  echo "Puppet > 4.8.2 is already installed"
  exit 1
fi
