#!/bin/bash

# when using daisy chaining on nvidia graphics card on debian,
# primary monitor is on but the rest of the daisy chained
# monitors are asleep, and does not wake up.
#
# below code forces the monitors to wake up

# only run xset commands if there are more than one monitors
if (( $(xrandr | grep -ce '\sconnected') > 1 ))
then
    xset dpms force off
    xset dpms force on
    xset dpms 0 0 0
fi
