#!/usr/bin/env python3
"""Suspend this desktop if not in use and lab is closed.

Contains a few checks (is anyone logged in, is Puppet running, etc.) before
shutting off.

If a kernel update is needed, the desktop will restart instead of suspending.
"""
import argparse
import os
import subprocess
import sys
from subprocess import DEVNULL

from ocflib.lab.hours import Day


def file_is_open(path):
    """Return whether a file is open by any process on the system."""
    return subprocess.call(('lsof', '--', path), stdout=DEVNULL, stderr=DEVNULL) == 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--force', '-f', action='store_true', help='force suspend, even if the lab is open')
    parser.add_argument('--quiet', '-q', action='store_true', help='stay quiet except for unexpected errors')
    args = parser.parse_args(argv)

    def report(line):
        if not args.quiet:
            print('[ocf-suspend] {}'.format(line), file=sys.stderr)

    # Don't sleep if...
    # ...lab is open
    if Day.from_date().is_open() and not args.force:
        report('not suspending as lab is open')
        return 1

    # ...we're installing packages
    if file_is_open('/var/lib/dpkg/lock'):
        report('not suspending as packages are installing')
        return 2

    # ...puppet is running
    if file_is_open('/var/lib/puppet/state/agent_catalog_run.lock'):
        report('not suspending as puppet is running')
        return 2

    # ...a user is logged in
    if subprocess.check_output(('w', '--no-header')):
        report('not suspending as user(s) are logged in')
        return 3

    # ...we're a virtual machine
    if subprocess.check_output(('imvirt')) != b'Physical\n':
        report('not suspending as this is not a physical machine')
        return 4

    report('checks passed, okay to suspend')

    # Try to remount /home to free up space.
    if subprocess.call(('umount', '/home')) != 0:
        report('not suspending as could not unmount /home')
        return 5

    subprocess.check_call(('mount', '/home'))

    reboot_needed = '/var/run/apt-dater-host_reboot'
    if os.path.isfile(reboot_needed):
        # Reboot because there's a kernel update.
        os.remove(reboot_needed)
        report('rebooting because of newer installed kernel')
        subprocess.check_call(('shutdown', '-r', 'now'), stdout=DEVNULL, stderr=DEVNULL)
    else:
        # Enable wake-on-LAN and go to sleep.
        report('going to sleep')
        subprocess.check_call(('/sbin/ethtool', '-s', 'eth0', 'wol', 'g'), stdout=DEVNULL, stderr=DEVNULL)
        if subprocess.call(('/usr/sbin/pm-suspend'), stdout=DEVNULL, stderr=DEVNULL) != 0:
            report('failed to suspend')


if __name__ == '__main__':
    exit(main())
