#!/bin/bash
# Don't sleep if installing packages, puppet is running, user present, or is a virtual machine

! /usr/bin/lsof -- /var/lib/dpkg/lock > /dev/null 2>&1 || exit 1
[ ! -f /var/lib/puppet/state/agent_catalog_run.lock ] || exit 1
[ $(w --no-header | wc -l) -eq 0 ] || exit 2

if grep $'tmpfs\t/home' /etc/fstab > /dev/null; then
	umount /home 2> /dev/null && mount /home || exit 3
fi

imvirt | grep -i Physical > /dev/null || exit 4

umount /tmp 2> /dev/null && mount /tmp

# Enable WOL and sleep until magic packet wakes you up
/sbin/ethtool -s eth0 wol g
/usr/sbin/pm-suspend > /dev/null
