#!/bin/bash
# Suspend the machine and wake on LAN.

# Don't sleep if...
# installing packages
! /usr/bin/lsof -- /var/lib/dpkg/lock > /dev/null 2>&1 || exit 1
# puppet is running
[ ! -f /var/lib/puppet/state/agent_catalog_run.lock ] || exit 2
# user present
[ $(w --no-header | wc -l) -eq 0 ] || exit 3
# is a virtual machine
imvirt | grep -qi Physical || exit 4

# Try to unmount /home and /tmp (both tmpfs)
if grep $'tmpfs\t/home' /etc/fstab > /dev/null; then
	umount /home 2> /dev/null && mount /home || exit 255
fi
umount /tmp 2> /dev/null && mount /tmp

# Check if a kernel update is needed, restart if so
if [ -f /var/run/apt-dater-host_reboot ]; then
    rm -f /var/run/apt-dater-host_reboot
    shutdown -r now > /dev/null 2>&1
fi

# Enable WOL and sleep until magic packet wakes you up
/sbin/ethtool -s eth0 wol g
/usr/sbin/pm-suspend > /dev/null
