#!/usr/bin/env python3
"""Enforcer is a prehook and posthook for Tea4CUPS the primary purpose of which
is to add and subtract remaining pages as user jobs are processed.

When a user sends a job to the print server, Tea4CUPS passes the job as a
PostScript file to enforcer before sending it to the printer. Enforcer calls
Ghostscript to count pages and connects to mysql to check against the user's
quota. If enforcer returns 255 (a.k.a. -1), the job is rejected. Otherwise,
enforcer gets called again when the job is done and logs the job in mysql,
taking care to set the page count to zero if an error was encountered.

Another function of enforcer is to send notifications to desktops to let users
know when a job has been sent to the printer, been rejected due to the quota,
finished printing, or failed to print.
"""
import argparse
import os
import subprocess
import sys
from collections import namedtuple
from configparser import ConfigParser
from datetime import datetime
from syslog import syslog
from textwrap import dedent
from traceback import format_exc

import ocflib.printing.quota as quota
from ocflib.constants import MAIL_SIGNATURE
from ocflib.misc.mail import send_mail_user
from ocflib.misc.mail import send_problem_report


CONF_FILE = '/opt/share/enforcer/enforcer.conf'


Message = namedtuple('Message', ['subject', 'body'])


USER_ERROR_INFO = dedent("""\
    Username: {user}
    Time: {time}
    File: {doc_name}
    Total pages: {pages}
    Pages left today: {daily_pages}
    Pages left this semester: {semester_pages}\
""")

INSUFFICIENT_QUOTA_MESSAGE = Message(
    subject='[OCF] Your latest print job was rejected',
    body=dedent("""\
        Greetings from the Open Computing Facility,

        This email is letting you know that your most recent print job was
        rejected since it would exceed your daily quota. The daily quota is
        {daily_quota} pages today and the semesterly quota is {semester_quota} pages.

        """) + USER_ERROR_INFO + dedent("""

        Does something look wrong? Please reply to

            help@ocf.berkeley.edu


        """) + MAIL_SIGNATURE
)

PRINTER_ERROR_MESSAGE = Message(
    subject='[OCF] Your latest print job failed',
    body=dedent("""\
        Greetings from the Open Computing Facility,

        This email is from the OCF to let you know that your most recent print
        job failed due to a printer error. If there's something wrong with the
        printers, please alert the publications staff at the desk.

        """) + USER_ERROR_INFO + dedent("""

        Still can't get it to print? Please reply to

            help@ocf.berkeley.edu


        """) + MAIL_SIGNATURE
)

ENFORCER_ERROR_MESSAGE = Message(
    subject='[OCF] Your latest print job failed',
    body=dedent("""\
        Greetings from the Open Computing Facility,

        This email is from the OCF to let you know that your most recent print
        job failed due to a problem with the print accounting system. OCF staff
        have been notified of the problem and should fix it shortly. If there
        is a staff member in lab, you can ask them for help in the meantime.

        """) + USER_ERROR_INFO + dedent("""

        Still can't get it to print? Please reply to

            help@ocf.berkeley.edu


        """) + MAIL_SIGNATURE
)


def read_config():
    conf = ConfigParser()
    conf.read(CONF_FILE)
    mysql_user = conf.get('enforcer', 'user')
    mysql_passwd = conf.get('enforcer', 'passwd')
    return mysql_user, mysql_passwd


def page_count(path):
    return int(subprocess.check_output(('/usr/local/bin/enforcer-pc', path), timeout=30))


def create_job(env):
    printer = env['TEAPRINTERNAME']
    queue = env['CLASS']
    return quota.Job(
        user=env['TEAUSERNAME'],
        time=datetime.now(),
        pages=page_count(env['TEADATAFILE']),
        queue=queue,
        printer=printer,
        doc_name=env['TEATITLE'],
        filesize=env['TEAJOBSIZE'],
    )


def send_printer_mail(message, job, quo):
    body = message.body.format(
        user=job.user,
        time=job.time,
        doc_name=job.doc_name,
        pages=job.pages,
        daily_pages=quo.daily,
        semester_pages=quo.semesterly,
        daily_quota=quota.daily_quota(),
        semester_quota=quota.SEMESTERLY_QUOTA,
    )
    send_mail_user(job.user, message.subject, body)


def prehook(c, job):
    quo = quota.get_quota(c, job.user)
    if job.pages > quo.daily:
        send_printer_mail(INSUFFICIENT_QUOTA_MESSAGE, job, quo)
        sys.exit(255)


def posthook(c, job, success):
    if success:
        quota.add_job(c, job)
    else:
        pass
#        quo = quota.get_quota(c, job.user)
#        send_printer_mail(PRINTER_ERROR_MESSAGE, job, quo)


def main(argv):
    job, quo = None, None
    try:
        parser = argparse.ArgumentParser(
            description=__doc__,
            formatter_class=argparse.RawDescriptionHelpFormatter,
        )
        parser.add_argument('command',
                            choices={'prehook', 'posthook'})
        args = parser.parse_args(argv[1:])
        job = create_job(os.environ)
        with quota.get_connection(*read_config()) as c:
            if args.command == 'prehook':
                prehook(c, job)
            else:
                success = os.environ['TEASTATUS'] == '0'
                posthook(c, job, success)
    except SystemExit as e:
        sys.exit(e.code)
    except:
        msg = dedent("""\
            enforcer encountered the following error while processing a job:

            {traceback}


            tea4cups environment variables:
            {vars}
            """).format(
            traceback=format_exc(),
            # seems unlikely a non-tea4cups var will start with TEA
            vars='\n'.join('  {}: {}'.format(k, v) for k, v in
                           os.environ.items() if k.startswith('TEA'))
        )

        syslog(msg)
        send_problem_report(msg)
        if job:
            try:
                send_printer_mail(
                    ENFORCER_ERROR_MESSAGE,
                    job,
                    quo or quota.UserQuota(user=job.user, daily='Unknown',
                                           semesterly='Unknown')
                )
            except:
                pass
        # Don't retry; it's not going to print the second time.
        sys.exit(255)


if __name__ == '__main__':
    main(sys.argv)
