#!/usr/bin/env python3
"""A Tea4CUPS filter which resizes the input Postscript to US Letter."""
import os
import subprocess
import sys


def mb(b):
    return b / 1024 / 1024


def do_filter(instream, outstream):
    """Force resize to US Letter, and mark as duplex (or not)."""
    is_duplex = os.environ.get('CLASS') != 'single'
    original_ps = instream.read()

    print('original: {:.2f} MB'.format(mb(len(original_ps))), file=sys.stderr)

    # stage one: rasterize with imagemagick
    rasterized = subprocess.check_output((
        'convert', '-density', '300', '-compress', 'Group4', 'ps:-', 'ps:-',
    ), input=original_ps)
    print('rasterized: {:.2f} MB'.format(mb(len(rasterized))), file=sys.stderr)

    open('rasterized.ps', 'wb').write(rasterized)

    # stage two: fit to letter, apply duplex
    final = subprocess.check_output(
        (
            'gs',
            '-q',
            '-dBATCH',
            '-dNOPAUSE',
            '-sDEVICE=ps2write',
            '-sOutputFile=-',
            '-sPAPERSIZE=letter',
            '-dFIXEDMEDIA',
            '-dPSFitPage',
        ) +
        (
            (
                '-c',
                '<</PSDocOptions (<< /Duplex true >> setpagedevice)>> setdistillerparams',
            ) if is_duplex else ()
        ) +
        ('-f', '/dev/stdin'),
        input=rasterized,
    )
    print('final: {:.2f} MB'.format(mb(len(final))), file=sys.stderr)

    outstream.write(final)


if __name__ == '__main__':
    do_filter(sys.stdin.buffer, sys.stdout.buffer)
