#!/bin/sh -eu
/usr/local/bin/rsync-no-vanished -rlptyH --delay-updates --delete-delay --exclude debug/ -v \
	 rsync://stage.opensuse.org/opensuse-full-really-everything/opensuse/ /opt/mirrors/ftp/opensuse
