#!/usr/bin/env python
import ldap

LDAP_SERVER = 'ldaps://ldap.ocf.berkeley.edu/'
LDAP_BASE = 'ou=Hosts,dc=OCF,dc=Berkeley,dc=EDU'

l = ldap.initialize(LDAP_SERVER)
l.simple_bind_s('', '')

attrs = ('cn', 'ipHostNumber', 'type', 'puppetVar')

# Only load servers and desktops to avoid trying to contact printers, dhcp, etc.
for _, vals in l.search_st(LDAP_BASE, ldap.SCOPE_SUBTREE, '(|(type=server)(type=desktop))', attrs):
    cn, ip, host_type, puppet_var = map(lambda key: vals.get(key, [''])[0], attrs)

    # Don't include hozer machines
    if cn.startswith('hozer-'):
        continue

    print('[{}.ocf.berkeley.edu]'.format(cn))
    print('\taddress {}'.format(ip))

    # Disable alerting on staff VMs
    if puppet_var.startswith('owner'):
        print('\tcontacts none')
