#!/usr/bin/env python3
"""Generate a list of hosts to give to munin for stats generation"""
from ocflib.infra.hosts import hosts_by_filter

# Only load servers, desktops, and staff VMs to avoid trying to contact anything
# not running munin, like printers, anything on dhcp, the switch, etc.
for vals in hosts_by_filter('(|(type=server)(type=desktop)(type=staffvm))'):
    cn, ip, host_type = vals['cn'][0], vals['ipHostNumber'][0], vals['type'][0]

    # Don't include hozer machines
    if cn.startswith('hozer-'):
        continue

    print('[{}.ocf.berkeley.edu]'.format(cn))
    print('\taddress {}'.format(ip))

    # Disable alerting on staff VMs
    if host_type == 'staffvm':
        print('\tcontacts no')
