#!/usr/bin/env python3
import json
import sys
from datetime import datetime
from datetime import timedelta

import dateutil.parser


ONE_HOUR = timedelta(hours=1)


if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] == 'config':
        print('graph_title mails sent past hour')
        print('graph_vlabel mails sent past hour')
        print('graph_scale no')
        print('mails_last_hour.label mails sent past hour')
        exit(0)

    count = 0
    now = datetime.now()
    for name in ('ocfmail.log', 'ocfmail.log.1'):
        with open('/var/log/' + name) as f:
            for line in f:
                record = json.loads(line)
                to = (record['to'] or [None, None])[1]
                # request tracker?
                if to is None:
                    continue
                # workaround rt#4299
                try:
                    if (to or '').lower() == 'root@ocf.berkeley.edu':
                        continue
                except AttributeError:
                    pass
                if now - dateutil.parser.parse(record['date']) > ONE_HOUR:
                    continue
                count += 1

    print('mails_last_hour.value {}'.format(count))
