#!/usr/bin/env python3
"""Dump a list of virtual host information in JSON.

The purpose of the JSON is so that a simple Ruby fact can execute this script
and parse the JSON into a custom Facter fact, made available in Puppet.

Unfortunately Facter requires structured facts to be written in Ruby.
"""
import json
import os.path

from ocflib.account.utils import get_vhosts
from ocflib.account.utils import web_dir


if __name__ == '__main__':
    print(json.dumps(
        [
            dict(
                {
                    # Some of these are calculate in Puppet's limited DSL, so
                    # we do them here even though they're redundant.
                    'domain': domain,
                    'web_dir': web_dir(vhost['username']),
                    'use_ssl': 'ssl' in vhost['flags'],
                    'use_hsts': 'hsts' in vhost['flags'],
                    'full_docroot': os.path.join(
                        web_dir(vhost['username']),
                        vhost['docroot'].lstrip('/'),
                    ),
                    # If it's an HTTPS site, we need to add an HTTP alias for the main domain.
                    'http_aliases': vhost['aliases'] + ([domain] if 'ssl' in vhost['flags'] else []),
                    # TODO: adjust ocflib to just provide this now that we
                    # don't need the full Apache string
                    'redirect_dest': None if not vhost['redirect'] else vhost['redirect'].split()[1],
                },
                **vhost
            )
            for domain, vhost in get_vhosts().items()
        ],
        indent=True,
    ))
