#!/bin/sh

# daradib@OCF, 2012-07-04

set -e

usage(){
  echo "Usage: '`basename $0` [ENVIRONMENT]'"
  echo "This script (requires root) displays the local node's Puppet environment,"
  echo "and changes it to ENVIRONMENT (alphanumeric-only), if provided."
}

# process arguments, basic sanitization
if [ $# -gt 2 ]; then
  usage
  exit 1
elif [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
  usage
  exit
else
  env_new="`echo "$1" | tr -cd '[:alnum:]'`"
fi

# require root privileges
if [ "`id -u`" != '0' ]; then
  echo 'Error: requires root privileges.' 1>&2
  exit 2
fi

# define functions to retrieve and set environment
get_env(){ /usr/bin/puppet config print environment --run_mode agent; }
set_env(){ /bin/echo -e "set /files/etc/puppet/puppet.conf/agent/environment $env_new\nsave" | /usr/bin/augtool > /dev/null; }

echo "Current environment: `get_env`"

# if provided, set environment
if [ -n "$env_new" ]; then

  # augeas-tools needs to be installed
  [ -x /usr/bin/augtool ] || ( echo 'Error: augtool not found' 1>&2; exit 2 )

  set_env
  echo "New     environment: `get_env`"

fi
