#!/usr/bin/env python3
"""Update or acquire Let's Encrypt certificates for a host.

This script is triggered every time Puppet runs with the host's domain
name(s) in the arguments. It is also triggered by other scripts, e.g.
the Let's Encrypt scripts for vhosts on www and apphost.

The script takes the following basic steps to acquire a certificate:

    1. Checks if we have already acquired this certificate in the past.

    2. If we already have a cert, further checks the expiration date to
       see if it is expired or going to expire within a few weeks.

    3. If the answer to (1) or (2) is "no", we invoke acme-tiny to
       acquire/renew the cert.

Sounds simple enough? Well, there's more to it. acme-tiny proves that we
actually own the domains by writing a challenge file and expecting it to
be served under http://<fqdn>/.well-known/acme-challenge/. This presents
two problems: 1) on hosts that don't run a web server (e.g. mail), we
need something to serve that file, and 2) on hosts that do run a web
server, we may need to acquire the cert before the web server can even
start.

Our solution is to enforce the following assumption: if there is a
running web server, it MUST serve up the challenge directory at
http://<fqdn>/.well-known/acme-challenge. This simplifies our logic to
the following:

    1. If there's something already listening on port 80, just make any
       needed certificate requests and expect them to succeed; the
       running web server will handle it.

    2. If not, then we're either bootstrapping or the host doesn't run a
       web server. In this case, we start a temporary server (Python's
       http.server) to serve the challenge files while making requests
       and shut it down when we're finished.

It is also possible for us to hit our rate limit for Let's Encrypt
requests, but our limit as of writing is 1000 new certs per week with
unlimited renewals, so this is only possible in case of catastrophic
failure (i.e. we lose all of our web vhost certs).

Once the needed certs are acquired, the corresponding .pem and .bundle
files still have to be generated. This is left to the caller, i.e.
puppet or a host-specific script.

The return code indicates whether the script did anything, so the caller
can reload services as necessary:

    0       nothing changed
    255     cert renewed/acquired
    else    error
"""
import argparse
import functools
import os
import re
import socket
import subprocess
import sys
import tempfile
from contextlib import contextmanager
from datetime import datetime
from datetime import timedelta
from datetime import timezone
from pathlib import Path

import dateutil.parser
from OpenSSL import crypto


RENEW_WHEN_TIME_REMAINING = timedelta(days=45)

LE_ACCOUNT_KEY = Path('/etc/ssl/lets-encrypt/le-account.key')
ACME_BASE_DIR = Path('/var/lib/lets-encrypt/')


def debug(*args, **kwargs):
    pass


def expiration_date(cert_path):
    with cert_path.open('rb') as f:
        cert = crypto.load_certificate(crypto.FILETYPE_PEM, f.read())
    return dateutil.parser.parse(cert.get_notAfter())


def cert_status(cert_path):
    if cert_path.exists():
        expires = expiration_date(cert_path)
        time_remaining = expires - datetime.now(timezone.utc)
        if time_remaining > RENEW_WHEN_TIME_REMAINING:
            return False, time_remaining
        else:
            return True, time_remaining
    else:
        return True, None


@contextmanager
def make_csr(domains, key_path):
    req = crypto.X509Req()
    req.get_subject().CN = domains[0]

    with open(key_path, 'rt') as f:
        key = crypto.load_privatekey(crypto.FILETYPE_PEM, f.read())
        req.set_pubkey(key)

    req.add_extensions((crypto.X509Extension(
        b'subjectAltName',
        False,
        bytes(', '.join('DNS:' + domain for domain in domains), encoding='ascii'),
    ),))

    req.sign(key, 'sha256')

    with tempfile.NamedTemporaryFile() as csr:
        csr.write(crypto.dump_certificate_request(crypto.FILETYPE_PEM, req))
        csr.flush()
        yield csr.name


def acme_tiny(domains, key_path):
    with make_csr(domains, key_path) as csr_path:
        # TODO: use subprocess.run when we get python3.5
        proc = subprocess.Popen(
            (
                'acme-tiny',
                '--account-key', str(LE_ACCOUNT_KEY),
                '--csr', csr_path,
                '--acme-dir', str(ACME_BASE_DIR / '.well-known' / 'acme-challenge'),
                # '--ca', 'https://acme-staging.api.letsencrypt.org',
            ),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        stdout, stderr = proc.communicate()
    return stdout, stderr, proc.returncode


def write_cert(cert, cert_path):
    """Write certificate file."""
    with tempfile.NamedTemporaryFile(
        dir=str(cert_path.parent),
        prefix='.tmp',
        delete=False,
    ) as temp_cert:
        try:
            temp_cert.write(cert)
            # atomic overwrite in case of errors
            os.chmod(temp_cert.name, 0o644)
            os.rename(temp_cert.name, str(cert_path))
        finally:
            try:
                os.remove(temp_cert.name)
            except FileNotFoundError:
                pass


def make_request(domains, cert_path, key, dry_run=False):
    """Makes a Let's Encrypt certificate request."""
    for domain in domains:
        assert re.match(r'^[a-z\-_\.0-9]+$', domain)
    if not dry_run:
        try:
            cert, stderr, returncode = acme_tiny(domains, key)
            assert returncode == 0, returncode
            write_cert(cert, cert_path)
        except Exception:
            print('An error occured!', file=sys.stderr)
            print('stderr from acme-tiny:', file=sys.stderr)
            for line in stderr.decode().split('\n'):
                print('>', line, file=sys.stderr)
            raise


@contextmanager
def maybe_start_webserver(dry_run):
    if not dry_run and socket.socket().connect_ex(('127.0.0.1', 80)) != 0:
        proc = subprocess.Popen(
            ('python3', '-m', 'http.server', '80'),
            cwd=str(ACME_BASE_DIR),
        )

        # Wait for server to start up before proceeding
        while socket.socket().connect_ex(('127.0.0.1', 80)) != 0:
            assert proc.poll() is None, proc.returncode

        yield proc

        proc.terminate()
        try:
            proc.wait(timeout=10)
            print('Stopped ephemeral web server on port 80')
        except subprocess.TimeoutExpired:
            # Might not be possible, but kill
            proc.kill()
            print('Force-stopped ephemeral web server on port 80')
    else:
        yield None


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument('-n', '--dry-run', action='store_true')
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument(
        '--extended-return-codes',
        action='store_true',
        help='Use extended return codes:\n'
             '    254     cert renewed\n'
             '    255     cert acquired',
    )
    parser.add_argument(
        '--private-key',
        required=True,
        help='Path to the private SSL key for the cert.',
    )
    parser.add_argument(
        '--cert',
        required=True,
        help='Path to find and store the acquired cert.',
    )
    parser.add_argument(
        'domains',
        nargs='+',
        help='List of domains the cert should have on it. '
             'The first name will become the subject common name.',
    )
    args = parser.parse_args()

    if args.verbose:
        global debug
        debug = functools.partial(print, flush=True)

    cert_path = Path(args.cert)
    needs_replaced, time_remaining = cert_status(cert_path)
    if needs_replaced:
        with maybe_start_webserver(dry_run=args.dry_run):
            if time_remaining:
                print('Renewing {} (remaining: {})'.format(cert_path.name, time_remaining))
                ret = 254
            else:
                print('Acquiring {}'.format(cert_path.name))
                ret = 255

            make_request(args.domains, cert_path, args.private_key, args.dry_run)
            return ret if args.extended_return_codes else 255
    else:
        debug('Not renewing {} (remaining: {})'.format(cert_path.name, time_remaining))
        return 0


if __name__ == '__main__':
    sys.exit(main())
