#!/bin/sh -eu
/usr/local/bin/rsync-no-vanished -avzH --delete --delete-after --delay-updates --safe-links  --password-file /opt/mirrors/project/blender/password \
        ocfberkeley@download.blender.org::blender /opt/mirrors/ftp/blender
