#!/bin/sh -eu
/usr/local/bin/rsync-no-vanished -avzH --delete --delete-after --delay-updates --safe-links --password-file /opt/mirrors/project/blender/sync_password \
        ocfberkeley@rsync.download.blender.org::blender /opt/mirrors/ftp/blender
