#!/bin/bash

# Don't sleep if installing packages or puppet is running
! /usr/bin/lsof -- /var/lib/dpkg/lock > /dev/null 2>&1 || exit 1
[ ! -f /var/lib/puppet/state/agent_catalog_run.lock ] || exit 1

if grep "tmpfs /home" /proc/mounts > /dev/null; then
	# Continue only if previous command succeeds unless forced
	# Reset tmpfs-mounted directories
	if [ -z "$1" ]; then
		umount /home && mount /home || exit 2
		umount /tmp && mount /tmp
	elif [ "$1" = '--silent' ]; then
		umount /home 2> /dev/null && mount /home || exit 2
		umount /tmp 2> /dev/null && mount /tmp
	elif [ "$1" = '-f' -o "$1" = '--force' ]; then
		umount /home && mount /home
		umount /tmp && mount /tmp
	else
		exit 1
	fi
fi

# Enable WOL and sleep until magic packet wakes you up
/sbin/ethtool -s eth0 wol g
/usr/sbin/pm-suspend > /dev/null
