#!/bin/bash
# adopted from https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Rsync

OPTS=(--quiet --recursive --links --perms --times -D --delete "--timeout=300" --checksum)

SRC="rsync://masterdistfiles.gentoo.org/gentoo" # OSUOSL
DST="/opt/mirrors/ftp/gentoo-distfiles/"

echo "Started update at" "$(date)" >> "$0".log 2>&1
logger -t rsync "re-rsyncing the gentoo-distfiles tree"
/usr/bin/rsync "${OPTS[@]}" "${SRC}" "${DST}" >> "$0".log 2>&1

echo "End: " "$(date)" >> "$0".log 2>&1
