#!/usr/bin/env python3
"""Test if the Debian-style or timestamp mirror hasn't been updated recently.

This detects most problems caused by both failed syncs to our direct upstream
as well as cases where the upstream is out-of-date.

Ideally, the upstream url argument should refer to the *actual* upstream (e.g. Debian's
authoritative archive) and not just our upstream mirror (e.g.
mirrors.kernel.org).
"""
import argparse
import sys
from collections import namedtuple
from datetime import datetime
from datetime import timedelta

import dateutil.parser
import requests

Mirror = namedtuple('Mirror', ['url', 'updated_at'])


def update_func(healthcheck):
    if healthcheck == 'debian':
        return get_updated_debian
    elif healthcheck == 'manjaro':
        return get_updated_manjaro
    elif healthcheck == 'unix_timestamp':
        return get_updated_unix_timestamp
    elif healthcheck == 'datetime':
        return get_updated_datetime
    elif healthcheck == 'recursive_ls':
        return get_updated_recursive_ls
    else:
        raise ValueError('Unsupported type: {}'.format(healthcheck))


def get_updated_datetime(mirror_url):
    """Find the time the host was last synced.
    The first line on the page should be a datetime, e.g. Fri Jan 19 20:15:01 UTC 2018.
    >>> get_updated_datetime(mirror_url)
    datetime.datetime(2018, 1, 19, 20, 15, 1, tzinfo=tzutc())
    """
    req = requests.get(mirror_url)
    req.raise_for_status()
    return dateutil.parser.parse(req.text.splitlines()[0])


def get_updated_unix_timestamp(mirror_url):
    """Find the time the host was last synced.
    The first line on the page should be a unix timestamp, e.g. 1516392227.
    >>> get_updated_unix_timestamp(mirror_url)
    datetime.datetime(2018, 1, 19, 20, 3, 47)
    """
    req = requests.get(mirror_url)
    req.raise_for_status()
    return datetime.utcfromtimestamp(int(req.text.split()[0]))


def get_updated_recursive_ls(mirror_url):
    """Find the time the host was last synced.
    Should contain the output of ls -lR
    >>> get_updated_recursive_ls(mirror_url)
    datetime.datetime(2018, 1, 24, 10, 3)
    """
    req = requests.get(mirror_url)
    req.raise_for_status()
    # Ex: drwxr-xr-x  3 ftpadmin packager   3 2009-09-21 14:51 3.5.6
    # Splits on date and time, giving us "2009-09-21 14:51"
    dates = [' '.join(line.split()[5:7]) for line in req.text.splitlines()
             if len(line.split()) == 8]
    return dateutil.parser.parse(max(dates))


def get_updated_debian(mirror_url):
    """Find the time the host was last synced.
    The page of should have a line of the form "Date: Fri, 19 Jan 2018 19:26:41 UTC"
    >>> get_updated_debian(mirror_url)
    datetime.datetime(2018, 1, 19, 19, 26, 41, tzinfo=tzutc())
    """
    req = requests.get(mirror_url)
    req.raise_for_status()
    updated_line, = [line for line in req.text.splitlines() if line.startswith('Date: ')]
    return dateutil.parser.parse(updated_line.split(': ', 1)[1])


def get_updated_manjaro(mirror_url):
    """Find the time the host was last synced.
    Line in question should be of the form "date=2018-01-25T21:52:18Z"
    >>> get_updated_manjaro(mirror_url)
    datetime.datetime(2018, 1, 25, 21, 52, 18, tzinfo=tzutc())
    """
    req = requests.get(mirror_url)
    req.raise_for_status()
    updated_line, = [line for line in req.text.splitlines() if line.startswith('date=')]
    return dateutil.parser.parse(updated_line.split('=', 1)[1])


def get_mirrors(url_first, url_second, get_updated):
    """Given two mirror urls, return two Mirror
    namedtuples ordered (asc) by sync date."""
    mirror_first = Mirror(url_first, get_updated(url_first))
    mirror_second = Mirror(url_second, get_updated(url_second))
    return (min(mirror_first, mirror_second, key=lambda z: z.updated_at),
            max(mirror_first, mirror_second, key=lambda z: z.updated_at))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('project', type=str, help='Project title')
    parser.add_argument('url_first', type=str, help='URL of local or upstream mirror')
    parser.add_argument('url_second', type=str, help='URL of local or upstream mirror')
    parser.add_argument('-t', '--type', type=str, default='debian')

    # ensure we aren't comparing a mirror against itself
    args = parser.parse_args()
    if args.url_first == args.url_second:
        print('Local and upstream urls cannot be equal... Exiting!')
        sys.exit(1)

    # Assume our mirror is out of date
    local_mirror, upstream_mirror = get_mirrors(args.url_first, args.url_second, update_func(args.type))

    # instead of comparing against current time, compare against the master server;
    # this helps avoid flaky monitoring if the upstream archive isn't updated
    delta = upstream_mirror.updated_at - local_mirror.updated_at
    if delta > timedelta(hours=24):
        print('Warning: {} has not been updated in {}'.format(args.project, delta))
        print('    Local mirror: {}'.format(local_mirror.updated_at))
        print('        {}'.format(local_mirror.url))
        print('    Upstream mirror: {}'.format(upstream_mirror.updated_at))
        print('        {}'.format(upstream_mirror.url))
        sys.exit(1)

# vim: ft=python
