#!/bin/bash
# Generate a "sizes" file in /opt/mirrors/ftp for convenience of us and any
# curious internet people.
set -euo pipefail

{
    /sbin/zfs list | /usr/bin/awk '{printf("%-30s %-10s\n", $1, $2);}'
    echo
    echo -n 'Last updated: '
    date
} | sponge /opt/mirrors/ftp/sizes
